server:
  port: 8082

spring:
  data:
    mongodb:
      database: bookshelf

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
